package ge.edu.tsu.hrs.control_panel.model.imageprocessing;

public enum ImageCondition {
	DARK_ON_BRIGHT,
	BRIGHT_ON_DARK,
	DARK_ON_PARTI_BRIGHT,
	BRIGHT_ON_PARTI_DARK,
	DARK_ON_BRIGHT_WITH_SOME_NOISE,
	BRIGHT_ON_DARK_WITH_SOME_NOISE,
	DARK_ON_BRIGHT_WITH_MUCH_NOISE,
	BRIGHT_ON_DARK_WITH_MUCH_NOISE,
	DARK_ON_BRIGHT_WITH_LINES,
	BRIGHT_ON_DARK_WITH_LINES,
	UNKNOWN
}
